### ISSUE TITLE
rockspec does not build

### ISSUE THREAD

**Issue by nopdotcom** [lua-stdlib/functional#3]
After fixing the URL to `https://github.com/lua-stdlib/functional/raw/master/std.functional-git-1.rockspec`:

```sh
$ sudo luarocks install https://github.com/lua-stdlib/functional/raw/master/std.functional-git-1.rockspec

Using https://github.com/lua-stdlib/functional/raw/master/std.functional-git-1.rockspec... switching to 'build' mode
Cloning into 'functional'...
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 25 (delta 0), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (25/25), 28.70 KiB | 0 bytes/s, done.
Checking connectivity... done.
stat: cannot stat 'lib/std/functional/version.lua': No such file or directory

Error: Build error: Failed installing lib/std/functional/version.lua in /usr/local/lib/luarocks/rocks/std.functional/git-1/lua/std/functional/version.lua

$
```

**Comment by gvvaughan** [comment]
Interesting.  Both URLs work for me; and I got the one I used by clicking through the github UI to the raw content of the rockspec file. As I noted in your other issue, I'll fix that everywhere in case you need write access to get the one I'm quoting or something...

The version.lua file is generated by the Makefile, so you can clone the repo, run 'make' to generate the version.lua source, and then `luarocks make *.rockspec` or similar.  Nonetheless, I'll fix this so that the instructions in all my README files are true again :)
